---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

``` {r setup, include=FALSE}
#--------------Packages-------------------------
library(devtools)
#devtools::install_github("RamiKrispin/coronavirus", force=T)
library(coronavirus)
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(htmltools)
library(dplyr)
library(DT)
library(plotly)
library(data.table)
library(lubridate)
#-------------Data-------------------------------
data("coronavirus")
df <- coronavirus

df_us <- df %>% 
            dplyr::filter(Country.Region=="US" & type=="confirmed" & cases >=1) %>%
            dplyr::group_by(Country.Region, Province.State, Lat, Long) %>% summarise(total_cases=sum(cases))

df_us <- df_us %>% 
          dplyr::filter( !(Province.State %in% c('Guam','U.','Puerto Rico')))


#----------Mapping-------------------------------
m <- leaflet() %>%
  addTiles() %>% 
  addCircleMarkers(
  lng=df_us$Long, lat=df_us$Lat,
  radius = ifelse(df_us$total_cases < 500, 4,ifelse(df_us$total_cases >=500 &  df_us$total_cases < 1000, 6,
                                                   ifelse(df_us$total_cases>=1000 & df_us$total_cases <5000,12,
                                                          ifelse(df_us$total_cases>=5000 & df_us$total_cases <15000,20,
                                                                 ifelse(df_us$total_cases>=15000 & df_us$total_cases <30000,30,
                                                                        ifelse(df_us$total_cases>=30000 & df_us$total_cases <40000,40,50)))))),
  color = "red",
  stroke = FALSE, fillOpacity = 0.5,
  label = htmlEscape(paste0(df_us$Province.State,",",df_us$total_cases)))


#---------comparison--------------------------------
df_topten <- df %>% 
                filter(df$Country.Region %in% c("China","Italy","Iran","Spain","Korea, South",
                                                "Germany","France","US","Switzerland","United Kingdom") & cases >= 1 & type=="confirmed")

df_topten <- df %>% 
                filter(df$Country.Region %in% c("China","Italy","Iran","Spain","US") & cases >= 1 & type=="confirmed")

df_topten <- df_topten %>% 
                group_by(Country.Region, date) %>%
                arrange(Country.Region, date)

df_topten <- data.table(df_topten, key = c("Country.Region"))
df_topten[, csum := cumsum(cases), by = key(df_topten)]

m
```


Map
=======================================================================
Row
-----------------------------------------------------------------------

### Covid-19 distribution across US
```{r}
m
```

Trend across countries.
=======================================================================
Row
-----------------------------------------------------------------------
### Trend across top 4 countries

```{r}
#-------- trend for top 10 countries -------------------------------
p <- df_topten %>% 
        plot_ly(x=~date, y=~csum, group=~Country.Region,color=~Country.Region, mode="lines") %>% 
        layout(xaxis = list( title="Date", hovermode = "compare",
                 margin =  list(
                   # l = 60,
                   # r = 40,
                   b = 10,
                   t = 10,
                   pad = 2
                 )))
p
```

### Cases by week of the year
```{r}
#-------------- Cases Per Week comparison ----------------------------------

df_topten$week <- lubridate::week(df_topten$date)
#table(df_topten$Country.Region, df_topten$week)


cases_per_week <- df_topten %>% 
                      group_by(Country.Region,week) %>% 
                        summarise(total_cases=sum(cases))


plot_per_week <- cases_per_week %>% 
                    plot_ly(x=~week, y=~total_cases, color=~Country.Region, type = "bar") %>% 
                    layout(xaxis = list( title="By week", tickmode = "linear"))

plot_per_week
```


Row 
-----------------------------------------------------------------------

### Trend across weeks 
```{r}
#------------------- comparison across week ---------------------------------------------------
cases_per_week <- data.table(cases_per_week)
cases_per_week <- cases_per_week[, `week_comp` := 1:.N, by = `Country.Region`]


plot_per_same_week_no <- cases_per_week %>% 
                    plot_ly(x=~week_comp, y=~total_cases, color=~Country.Region, type = "bar") %>% 
                    layout(xaxis = list( title="By week", tickmode = "linear"))

plot_per_same_week_no
```


